export const EVENTS = {
  CREATE_ROOM: 'CREATE_ROOM',
  ROOM_CREATED: 'ROOM_CREATED',
  JOIN_ROOM: 'JOIN_ROOM',
  JOINED_ROOM: 'JOINED_ROOM',
  PLAYER_JOINED: 'PLAYER_JOINED',
  PLAYER_LEFT: 'PLAYER_LEFT',
  START_GAME: 'START_GAME',
  GAME_STARTED: 'GAME_STARTED',
  GUESS_LETTER: 'GUESS_LETTER',
  ERROR: 'ERROR'
};
